language: node_js
node_js:
  - node
  - lts/*
cache:
  directories:
    - ~/.npm\
    - .jest
before_script:
  - npm install -g npm@latest
script:
  - npm ci
  # - npx jest --ci
  - npm test -- --coverage --updateSnapshot
  - npm run lint